<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-GMEKR49" failures="1" tests="1" name="com.qa.tests.TelkomppobTest" time="55.243" errors="0" timestamp="2020-08-11T14:50:46 ICT" skipped="0">
  <testcase classname="com.qa.tests.TelkomppobTest" name="belijastel3bPpob" time="55.243">
    <failure message="The following asserts failed:
	expected [11-08-20 14:50] but found [23-08-20 16:25],
	expected [TOTAL Rp.124.660] but found [124.660],
	expected [124.660] but found [125.000]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [11-08-20 14:50] but found [23-08-20 16:25],
expected [TOTAL Rp.124.660] but found [124.660],
expected [124.660] but found [125.000]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.qa.tests.TelkomppobTest.belijastel3bPpob(TelkomppobTest.java:456)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1380)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </failure>
  </testcase> <!-- belijastel3bPpob -->
  <system-out>
This is the sample screenshot <a href='C:\Users\acil\git\AppiumTDDFramework\Screenshots\Android_SM-T295-Bg-Acil\2020-08-11_14-49-27\TelkomppobTest\belijastel3bPpob.png'> <img src='C:\Users\acil\git\AppiumTDDFramework\Screenshots\Android_SM-T295-Bg-Acil\2020-08-11_14-49-27\TelkomppobTest\belijastel3bPpob.png' height='400' width='400'/> </a>  </system-out>
</testsuite> <!-- com.qa.tests.TelkomppobTest -->
